services:
  hub:
    image: selenium/hub
#    ports:
#    - 4444:4444
#   - 4442:4442
#   - 4443:4443

  chrome:
    image: selenium/node-chrome
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1
    shm_size: '2g'
    deploy:
      replicas: 1
  firefox:
    image: selenium/node-firefox
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1
    shm_size: '2g'
    deploy:
      replicas: 1
  vendor-portal:
    image: keshrsa/selenium-docker
    depends_on:
    - hub
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - /mnt/d/Selenium-Docker/results/vendor-portal/:/home/selenium-docker/test-output
  flight-reservation:
    image: keshrsa/selenium-docker
    depends_on:
    - hub
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - /mnt/d/Selenium-Docker/results/flight-reservation/:/home/selenium-docker/test-output
